// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0PXQkj0-cnKwpiRZt6Q6DlhbC_Qu77iY',
    appId: '1:986494809498:web:19ce4e839ce031899c7623',
    messagingSenderId: '986494809498',
    projectId: 'chatapp-38256',
    authDomain: 'chatapp-38256.firebaseapp.com',
    storageBucket: 'chatapp-38256.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkEIVciDHLlc23bBJeiSWl_KrSWxPuEPU',
    appId: '1:986494809498:android:47135118294f73f29c7623',
    messagingSenderId: '986494809498',
    projectId: 'chatapp-38256',
    storageBucket: 'chatapp-38256.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI9jsgxsoj0d_7AdkFW2yxmoB_zSRQxuM',
    appId: '1:986494809498:ios:07f120965acd40669c7623',
    messagingSenderId: '986494809498',
    projectId: 'chatapp-38256',
    storageBucket: 'chatapp-38256.appspot.com',
    androidClientId: '986494809498-9qucfalnoeqfj29p4cjicl2hjs4te7eh.apps.googleusercontent.com',
    iosClientId: '986494809498-2p21qhsrd84ilvh55ipir7p7n6rq40b4.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
